services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - AAP_URL=https://ansibleaap.chrobinson.com
      - AAP_TOKEN=${AAP_TOKEN}  # Set via environment variable for security
      - AAP_TEMPLATE_ID=66  # Replace with your actual template ID
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:-admin}  # Default: admin
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD:-password}  # Default: password (CHANGE IN PRODUCTION)
      - FLASK_DEBUG=True
    restart: unless-stopped
