services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - AAP_URL=https://ansibleaap.chrobinson.com
      - AAP_TOKEN=22tTr8IldpcV9A5w6mAgUxwkZLjHk7  # Your working token
      - AAP_TEMPLATE_ID=66  # Replace with your actual template ID
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=password
      - FLASK_DEBUG=True
    restart: unless-stopped
